name: Build Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-ubuntu-cmake-ninja:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Ubuntu 18.04",
              os: ubuntu-18.04,
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt-get -y -qq update
          apt-get -y -qq --no-install-recommends install \
            cmake \
            ninja-build \
            extra-cmake-modules \
      - name: Configure & Build
        uses: lukka/run-cmake@v3
        with:
          buildDirectory: ${{ runner.workspace }}/build/
          cmakeAppendedArgs: -G Ninja

  build-windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Server 2019",
              os: windows-2019,
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare vcpkg
        uses: lukka/run-vcpkg@v6
        id: runvcpkg
        with:
          vcpkgArguments: libarchive[core] openssl sqlite3
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgGitCommitId: ffa7fd27cfa29f206d1fd2ccfc722cad4aaeef3d
          vcpkgTriplet: x64-windows

      - name: Print Environment
        run: gci env:* | sort-object name

      - name: Configure & Build
        uses: lukka/run-cmake@v3
        with:
          buildDirectory: ${{ runner.workspace }}/build/
          cmakeAppendedArgs: -G Ninja
          useVcpkgToolchainFile: true
